export const UI_PAGES = [
  { name: "home", path: "/", heading: "Selamat Datang di Kaderisasi Salman" },
  {
    name: "activity",
    path: "/activity",
    heading: "Ayo Daftar Kegiatan di Kaderisasi Salman",
  },
  { name: "clubs", path: "/clubs", heading: "Klub di Kaderisasi Salman" },
  {
    name: "consultation",
    path: "/consultation",
    heading: "Ruang Curhat Kaderisasi Salman",
  },
  {
    name: "leaderboard",
    path: "/leaderboard",
    heading: "Leaderboard Kaderisasi Salman",
  },
  { name: "login", path: "/login", heading: "Masuk ke akun" },
  { name: "register", path: "/register", heading: "Buat akun" },
  { name: "forgot", path: "/forgot", heading: "Lupa password" },
  { name: "reset", path: "/reset?token=ui-preview", heading: "Ubah password" },
  { name: "onboarding", path: "/onboarding", heading: "Lengkapi Profil Anda" },
  { name: "privacy", path: "/privacy-policy", heading: "Kebijakan Privasi" },
  { name: "terms", path: "/terms-of-service", heading: "Syarat dan Ketentuan" },
  {
    name: "verify",
    path: "/certificate/verify",
    heading: "Verifikasi sertifikat",
  },
  {
    name: "verified",
    path: "/certificate/verify/CERT-UI",
    heading: "Hasil verifikasi",
  },
  {
    name: "not-found",
    path: "/page-does-not-exist",
    heading: "Halaman tidak ditemukan",
  },
  {
    name: "club-missing",
    path: "/clubs/not-an-id",
    heading: "Halaman tidak ditemukan",
  },
  {
    name: "certificate-missing",
    path: "/certificate/invalid_code",
    heading: "Sertifikat tidak ditemukan",
  },
  {
    name: "activity-detail",
    path: "/activity/kegiatan-uji-1",
    heading: "Pelatihan Kepemimpinan dan Kolaborasi Aktivis Salman",
  },
  {
    name: "join",
    path: "/activity/kegiatan-uji-1/join",
    heading: "Pelatihan Kepemimpinan dan Kolaborasi Aktivis Salman",
  },
  { name: "club-detail", path: "/clubs/1", heading: "Klub Kolaborasi Salman" },
  {
    name: "club-redirect",
    path: "/clubs/registration-info/1",
    heading: "Klub Kolaborasi Salman",
  },
  {
    name: "guest-form",
    path: "/custom-form/activity/1?slug=kegiatan-uji-1",
    heading: "Formulir Pendaftaran Kegiatan",
  },
  {
    name: "form-success",
    path: "/custom-form/activity/1/success",
    heading: "Pendaftaran Berhasil!",
  },
  {
    name: "profile",
    path: "/profile",
    heading: "Profil Saya",
    session: "ui-preview",
  },
  {
    name: "profile-activities",
    path: "/profile?tab=activity",
    heading: "Profil Saya",
    session: "ui-preview",
  },
  {
    name: "profile-prestasi",
    path: "/profile?tab=achievements",
    heading: "Profil Saya",
    session: "ui-preview",
  },
  {
    name: "profile-curhat",
    path: "/profile?tab=ruangcurhat",
    heading: "Profil Saya",
    session: "ui-preview",
  },
  {
    name: "status",
    path: "/status",
    heading: "Cek Status Kegiatan",
    session: "ui-preview",
  },
  {
    name: "status-empty",
    path: "/status",
    heading: "Cek Status Kegiatan",
    session: "ui-empty",
  },
  {
    name: "registration-detail",
    path: "/profile/activity/kegiatan-uji-1",
    heading: "Pelatihan Kepemimpinan dan Kolaborasi Aktivis Salman",
    session: "ui-preview",
  },
  {
    name: "achievement",
    path: "/leaderboard/submit",
    heading: "Kirim Prestasi Anda",
    session: "ui-preview",
  },
  {
    name: "achievement-edit",
    path: "/leaderboard/edit/1",
    heading: "Edit Prestasi",
    session: "ui-preview",
  },
  {
    name: "form",
    path: "/form/1",
    heading: "Formulir Pendaftaran Kegiatan",
    session: "ui-preview",
  },
  {
    name: "custom-form",
    path: "/custom-form/activity/1",
    heading: "Formulir Pendaftaran Kegiatan",
    session: "ui-preview",
  },
  {
    name: "independent-form",
    path: "/custom-form/independent/1",
    heading: "Formulir Pendaftaran Kegiatan",
    session: "ui-preview",
  },
  {
    name: "independent-success",
    path: "/custom-form/independent/1/success",
    heading: "Formulir Berhasil Dikirim!",
    session: "ui-preview",
  },
  {
    name: "club-form",
    path: "/custom-form/club/1",
    heading: "Formulir Pendaftaran Kegiatan",
    session: "ui-preview",
  },
  {
    name: "club-success",
    path: "/custom-form/club/2/success",
    heading: "Pendaftaran Berhasil!",
    session: "ui-preview",
  },
  {
    name: "certificate-waiting",
    path: "/certificate/1",
    heading: "Sertifikat belum diterbitkan",
    session: "ui-preview",
  },
  {
    name: "consultation-form",
    path: "/consultation",
    heading: "Ruang Curhat Kaderisasi Salman",
    session: "ui-preview",
  },
] as const;
