import {
  ACHIEVEMENT_STATUS_ENUM,
  ACHIEVEMENT_TYPE_ENUM,
} from "@/types/constants/achievement";

export const ACHIEVEMENT_STATUS_RENDER = {
  [ACHIEVEMENT_STATUS_ENUM.PENDING]: "Menunggu Persetujuan",
  [ACHIEVEMENT_STATUS_ENUM.APPROVED]: "Disetujui",
  [ACHIEVEMENT_STATUS_ENUM.REJECTED]: "Ditolak",
};

export const ACHIEVEMENT_STATUS_COLOR = {
  [ACHIEVEMENT_STATUS_ENUM.PENDING]: "yellow",
  [ACHIEVEMENT_STATUS_ENUM.APPROVED]: "green",
  [ACHIEVEMENT_STATUS_ENUM.REJECTED]: "red",
};

export const ACHIEVEMENT_TYPE_RENDER = {
  [ACHIEVEMENT_TYPE_ENUM.AKADEMIK]: "Akademik",
  [ACHIEVEMENT_TYPE_ENUM.KOMPETISI]: "Kompetisi",
  [ACHIEVEMENT_TYPE_ENUM.ORGANISASI]: "Organisasi",
};
