import assert from "node:assert/strict";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const root = fileURLToPath(new URL("../", import.meta.url));
const core = join(root, "node_modules/@mantine/core");
const output = join(root, "src/app/mantine.css");
const visited = new Set();
const styles = new Set(["baseline", "default-css-variables", "global"]);
const indexes = new Map();

function imports(path) {
  const text = readFileSync(path, "utf8");
  const runtime = /\.tsx?$/.test(path)
    ? ts.transpileModule(text, {
        compilerOptions: { module: ts.ModuleKind.ESNext, jsx: ts.JsxEmit.Preserve },
      }).outputText
    : text;
  const source = ts.createSourceFile(path, runtime, ts.ScriptTarget.Latest, true);
  return source.statements
    .filter(ts.isImportDeclaration)
    .filter((node) => !node.importClause?.isTypeOnly);
}

function visitPackage(name, bindings) {
  // Resolve named imports instead of following the barrel into every component.
  if (!indexes.has(name)) {
    const index = join(root, "node_modules", name, "esm/index.mjs");
    const exports = new Map();
    for (const node of imports(index)) {
      const names = node.importClause?.namedBindings;
      if (names && ts.isNamedImports(names)) {
        for (const specifier of names.elements) {
          exports.set(
            specifier.name.text,
            node.moduleSpecifier.text.startsWith(".")
              ? resolve(dirname(index), node.moduleSpecifier.text)
              : null,
          );
        }
      }
    }
    indexes.set(name, exports);
  }
  assert.ok(
    bindings && ts.isNamedImports(bindings),
    `Use named Mantine imports: ${name}`,
  );
  for (const binding of bindings.elements) {
    if (binding.isTypeOnly) continue;
    const exported = (binding.propertyName ?? binding.name).text;
    const path = indexes.get(name).get(exported);
    assert.ok(
      indexes.get(name).has(exported),
      `Cannot resolve ${name} export ${exported}; review CSS dependencies`,
    );
    if (path) visit(path);
  }
}

function visit(path) {
  if (visited.has(path)) return;
  visited.add(path);
  if (path.startsWith(core) && path.endsWith(".module.mjs")) {
    const name = path.split("/").at(-1).replace(".module.mjs", "");
    // Some components share a stylesheet; the installed source identifies its owner.
    assert.ok(readFileSync(join(core, "styles", `${name}.css`), "utf8"));
    styles.add(name);
  }
  for (const node of imports(path)) {
    const name = node.moduleSpecifier.text;
    if (
      name.startsWith("@mantine/") &&
      !name.includes("/styles") &&
      !["@mantine/hooks", "@mantine/form"].includes(name)
    ) {
      visitPackage(name, node.importClause?.namedBindings);
    } else if (name.startsWith(".") && path.includes("/node_modules/@mantine/")) {
      visit(resolve(dirname(path), name));
    }
  }
}

function scan(directory) {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) scan(path);
    else if (/\.(ts|tsx)$/.test(entry.name) && !/\.(test|spec|d)\./.test(entry.name)) {
      visit(path);
    }
  }
}
scan(join(root, "src"));

// Match Mantine's shipped cascade order, including shared component primitives.
const full = readFileSync(join(core, "styles.css"), "utf8");
const globals = ["baseline", "default-css-variables", "global"];
const components = [...styles].filter((name) => !globals.includes(name));
function position(name) {
  const css = readFileSync(join(core, "styles", `${name}.css`), "utf8");
  const selector = css.match(/\.m_[a-zA-Z0-9_]+/)?.[0];
  assert.ok(
    selector && full.includes(selector),
    `Cannot determine CSS order for ${name}`,
  );
  return full.indexOf(selector);
}
components.sort((a, b) => position(a) - position(b));
const content = [
  "/* Generated by npm run styles:mantine. Do not reorder: dependencies precede consumers. */",
  ...[...globals, ...components].map(
    (name) => `@import "@mantine/core/styles/${name}.css";`,
  ),
  "",
].join("\n");
if (process.argv.includes("--write")) writeFileSync(output, content);
else {
  assert.equal(
    readFileSync(output, "utf8"),
    content,
    "Mantine CSS dependencies changed. Run npm run styles:mantine and verify affected pages.",
  );
}
console.log(
  `Mantine CSS: ${styles.size} stylesheets cover application and extension dependencies.`,
);
